-- E-COMMERCE SALES & ANALYTICS SYSTEM

-- 1.CREATE DATABASE
CREATE DATABASE ecommerce_db;

USE ecommerce_db;

-- 2.CREATE CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    CITY VARCHAR(30)
);
-- 3.INSERT CUSTOMER DATA
INSERT INTO CUSTOMERS
VALUES
(1, 'Rahul Sharma', 'rahul.sharma@gmail.com', 'Mumbai'),
(2, 'Aisha Khan', 'aisha.khan@gmail.com', 'Dubai'),
(3, 'David Miller', 'david.miller@gmail.com', 'New York'),
(4, 'Sneha Reddy', 'sneha.reddy@gmail.com', 'Bangalore'),
(5, 'Arjun Nair', 'arjun.nair@gmail.com', 'Kochi');

-- 4.CREATE PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50),
    CATEGORY VARCHAR(30),
    PRICE DECIMAL(10,2),
    STOCK INT
);
-- 5. INSERT PRODUCT DATA 
INSERT INTO PRODUCTS
VALUES
(101, 'iPhone 15 Pro Max', 'Electronics', 159999, 12),
(102, 'MacBook Pro M3', 'Electronics', 249999, 8),
(103, 'Samsung Galaxy S24 Ultra', 'Electronics', 129999, 15),
(104, 'PlayStation 5 Console', 'Gaming', 54999, 18),
(105, 'Apple Watch Ultra 2', 'Wearables', 89999, 10);

-- 6. CREATE ORDER TABLE
CREATE TABLE ORDERS (
ORDER_ID INT PRIMARY KEY,
CUSTOMER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
ORDER_DATE DATE 
);
-- 7. INSERT ORDER DATA 
INSERT INTO ORDERS
VALUES
(1001, 1, 101, 1, '2026-05-01'),
(1002, 2, 102, 1, '2026-05-02'),
(1003, 3, 104, 2, '2026-05-03'),
(1004, 4, 105, 1, '2026-05-04'),
(1005, 5, 103, 1, '2026-05-05');

-- 8. CREATE PAYMENT TABLE
CREATE TABLE PAYMENTS(
PAYMENT_ID INT PRIMARY KEY,
ORDER_ID INT,
PAYMENT_METHOD VARCHAR(20),
PAYMENT_STATUS VARCHAR(20)
);
-- 8. INSERT PAYMENT DATA
INSERT INTO PAYMENTS
VALUES
(501, 1001, 'UPI', 'SUCCESS'),
(502, 1002, 'CARD', 'SUCCESS'),
(503, 1003, 'PAYPAL', 'SUCCESS'),
(504, 1004, 'COD', 'PENDING'),
(505, 1005, 'UPI', 'SUCCESS');

-- 10. VIEW ALL TABLES
SHOW TABLES;

-- 11. VIEW TABLE DATA

SELECT * FROM CUSTOMERS;
SELECT *FROM PRODUCTS;
SELECT *FROM ORDERS;

-- 12. CUSTOMER PURCHASE REPORT

SELECT CUSTOMERS.CUSTOMER_NAME,
PRODUCTS.PRODUCT_NAME,
PRODUCTS.PRICE,
ORDERS.QUANTITY,
ORDERS.ORDER_DATE 
FROM ORDERS
INNER JOIN CUSTOMERS
ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
INNER JOIN PRODUCTS
ON ORDERS.PRODUCT_ID= PRODUCTS.PRODUCT_ID;


-- 13.TOTAL REVENUE REPORT

SELECT SUM(PRODUCTS.PRICE *ORDERS.QUANTITY)
AS TOTAL_REVENUE
FROM ORDERS
INNER JOIN PRODUCTS
ON ORDERS.PRODUCT_ID = PRODUCTS.PRODUCT_ID;


-- 14.TOP SELLING PRODUCTS

SELECT PRODUCTS.PRODUCT_NAME,
       SUM(ORDERS.QUANTITY) AS TOTAL_SOLD
FROM ORDERS
INNER JOIN PRODUCTS
ON ORDERS.PRODUCT_ID = PRODUCTS.PRODUCT_ID
GROUP BY PRODUCTS.PRODUCT_NAME
ORDER BY TOTAL_SOLD DESC;

-- 15. PENDING PAYMENT REPORT

SELECT *
FROM PAYMENTS
WHERE PAYMENT_STATUS ='PENDING';


-- 16.PREMIUM PRODUCTS

SELECT PRODUCT_NAME ,PRICE 
FROM PRODUCTS 
WHERE PRICE>100000
ORDER BY PRICE DESC;

-- 17. LOW STOCK PRODUCTS 

SELECT PRODUCT_NAME STOCK
FROM PRODUCTS 
WHERE STOCK<10;

-- 18.INTERNATIONAL CUSTOMERS 

SELECT CUSTOMER_NAME ,CITY 
FROM CUSTOMERS 
WHERE CITY IN('DUBAI','LONDON','TORONTA','SYDNEY');

-- 19.PROJECT COMPLETED






